GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQcml5YW5zaHUgTmVnaSIsImlhdCI6MTcwNjExMTM2OCwiZXhwIjoxNzA2MTExMzgzLCJhdWQiOiI2NWFmYzc5NmU0YzFkMTE1NzFlODU2Y2UifQ.eZ3F2yvoww6-cnB3B7tXPlJB05aR_b6pheB8eVX6NwQ
###Login Route
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "negi11@gmail.com",
    "password": "1234"
}

###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "negi111001@gmail.com",
    "password": "1234"
}

###Refresh Token Route
Post http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQcml5YW5zaHUgTmVnaSIsImlhdCI6MTcwNjExMTM2OCwiZXhwIjoxNzA2MTExMzgzLCJhdWQiOiI2NWFmYzc5NmU0YzFkMTE1NzFlODU2Y2UifQ.eZ3F2yvoww6-cnB3B7tXPlJB05aR_b6pheB8eVX6NwQ"
}

###Logout Route
DELETE  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQcml5YW5zaHUgTmVnaSIsImlhdCI6MTcwNjExNDk3MywiZXhwIjoxNzA2MTE0OTg4LCJhdWQiOiI2NWFmYzc5NmU0YzFkMTE1NzFlODU2Y2UifQ.fORATQKVQCxQkCjwTuhI6Lz1xUq7bXcU6mGcLXMiz2g"
}



###
GET http://localhost:3000/auth/get_user/anshunegi1@gmail.com
Content-Type: application/json

###
POST http://localhost:3000/product/add_product
Content-Type: application/json

{
    "name": "Iphone 16",
    "description": "Iphone 16 Pro MAx",
    "price": "60000",
    "category": "Apple"
}